### ISSUE TITLE
Need a server instance

### ISSUE THREAD

**Issue by b1conrad** [Picolab/PLAN#2]
1. Create EC2 instance with elastic IP address
2. Install pico-engine@1.1.1
3. Install and configure `nginx`
4. Create certificate for the domain name PICO.picolabs.io
5. Make a child pico of the root pico to represent the entire network

**Comment by windley** [comment]
I would recommend the instructions I created for the pico engine I'm hosting on EC2. It's working well.

**Comment by windley** [comment]
Let me know when you need the domain name.

**Comment by b1conrad** [comment]
The instructions are [Pico Engine on EC2](https://picolabs.atlassian.net/wiki/spaces/PLM/pages/2391244801/Pico+Engine+on+EC2), and useful. Particularly the use of `yum` to keep the instance up to date.

I've decided to clone the existing instance, to keep everyone who opted in to byname as a founding member of the PLAN. So, first step is to remove those who had been loaded in as part of the fully-sharded database experiment.

**Comment by b1conrad** [comment]
The EC2 instance has been created (free tier for now at least) and associated with the elastic IP address `44.240.219.202` to which Phil will soon point the domain name `PLAN.picolabs.io`.

I have copied two of the HTML files in the docs folder to `.nvm/versions/node/v16.20.1/lib/node_modules/pico-engine/public/` so the the pico engine will serve them up, once port 80 (upgraded to post 443) reverse proxies to port 3000.

**Comment by windley** [comment]
Done. plan.picolabs.io. -> 44.240.219.202
